<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiveRepository extends EntityRepository
{
}
